openapi: 3.0.0
info:
  title: browse_manager
  version: v1
servers:
  - url: 'https://services.utelly.com/browse_manager/v1'
    description: prod
  - url: 'https://staging-services.utelly.com/browse_manager/v1'
    description: staging
  - url: 'https://dev-services.utelly.com/browse_manager/v1'
    description: dev
paths:
  '/content/creative_works/{guid}':
    parameters:
      - schema:
          type: string
        name: guid
        in: path
        required: true
    get:
      summary: Get a creative work
      tags:
        - Creative work management
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  creative_work:
                    $ref: ../models/CreativeWork.v1.yaml
                  _embedded:
                    type: array
                    items:
                      anyOf:
                        - $ref: ../models/Genre.v1.yaml
                        - $ref: ../models/ContentRating.v1.yaml
                        - $ref: ../models/Availability.v1.yaml
                        - $ref: ../models/Tag.v1.yaml
                        - $ref: ../models/Contributor.v1.yaml
                required:
                  - creative_work
              examples:
                '1':
                  value:
                    creative_work:
                      guid: 27c13eec19014084a0a3173061702b46
                      metadata:
                        type: movie
                      created_at: '2020-01-01T00:00:10Z'
                      updated_at: '2020-01-01T00:00:10Z'
                      _links:
                        self:
                          href: /content/creative_works/27c13eec19014084a0a3173061702b46
                      identifiers:
                        - source: mysource
                          id: '1'
                          url: 'https://mydomain.com/myressource.html'
                      titles:
                        - metadata:
                            source: mysource
                            type: official
                            country: gb
                            language: en
                          title: The Usual Suspects
                      descriptions:
                        - metadata:
                            source: mysource
                            type: full
                            country: gb
                            language: en
                          description: 'A sole survivor tells of the twisty events leading up to a horrific gun battle on a boat, which began when five criminals met at a seemingly random police lineup.'
                      artworks:
                        - metadata:
                            source: mysource
                            type: poster
                            country: gb
                            language: en
                          url: 'https://mydomain.com/poster.jpg'
                          width: 100
                          height: 100
                      parent:
                        href: /content/creative_works/eac7cb1192264b088ccbad0874395ce5
                    _embedded:
                      - guid: 9be42f99a8ab420082719d1bafc8e649
                        identifiers:
                          - source: mysource
                            id: '1'
                        names:
                          - metadata:
                              language: en
                            name: Action
                        _links:
                          self:
                            href: /content/genres/9be42f99a8ab420082719d1bafc8e649
                        created_at: '2020-01-01T00:00:00Z'
                        updated_at: '2020-01-01T00:00:00Z'
      operationId: v1.content.creative_works.get
      security:
        - Authorization: []
      parameters:
        - schema:
            type: array
            items:
              type: string
              enum:
                - genres
                - tags
                - availabilities
                - content_ratings
                - contributors
            minItems: 1
          in: query
          name: embed
          explode: false
          description: ''
          style: form
        - schema:
            type: array
            items:
              $ref: '#/components/schemas/Languages'
            minItems: 1
          in: query
          name: languages
          description: ''
          style: form
        - schema:
            type: array
            items:
              type: string
              enum:
                - titles
                - descriptions
                - artworks
                - contributors
                - genres
                - tags
                - availabilities
                - content_ratings
                - parents
            minItems: 1
          in: query
          name: fields
      description: ''
  /content/creative_works:
    get:
      summary: List creative works
      tags:
        - Creative work management
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  creative_works:
                    type: array
                    items:
                      $ref: ../models/CreativeWork.v1.yaml
              examples:
                '1':
                  value:
                    creative_works:
                      - guid: 27c13eec19014084a0a3173061702b46
                        metadata:
                          type: movie
                        created_at: '2020-01-01T00:00:10Z'
                        updated_at: '2020-01-01T00:00:10Z'
                        _links:
                          self:
                            href: /content/creative_works/27c13eec19014084a0a3173061702b46
                        identifiers:
                          - source: mysource
                            id: '1'
                        titles:
                          - metadata:
                              source: mysource
                              type: official
                              country: gb
                              language: en
                            title: The Usual Suspects
                        descriptions:
                          - metadata:
                              source: mysource
                              type: full
                              country: gb
                              language: en
                            description: 'A sole survivor tells of the twisty events leading up to a horrific gun battle on a boat, which began when five criminals met at a seemingly random police lineup.'
                        artworks:
                          - metadata:
                              source: mysource
                              type: poster
                              country: gb
                              language: en
                            url: 'https://mydomain.com/poster.jpg'
                            width: 100
                            height: 100
                        contributors:
                          - _links:
                              self:
                                href: /content/contributors/7fd093bc626b4f458eb7a67cea0bfd53
                            role: actor
                        genres:
                          - _links:
                              self:
                                href: /content/genres/eac7cb1192264b088ccbad0874395ce5
                        tags:
                          - _links:
                              self:
                                href: /content/tags/eac7cb1192264b088ccbad0874395ce5
                        availabilities:
                          - _links:
                              self:
                                href: /content/availabilities/eac7cb1192264b088ccbad0874395ce5
                        content_ratings:
                          - _links:
                              self:
                                href: /content/content_ratings/eac7cb1192264b088ccbad0874395ce5
                        parent:
                          href: /content/creative_works/eac7cb1192264b088ccbad0874395ce5
      operationId: v1.content.creative_works.get_list
      description: ''
      security:
        - Authorization: []
      parameters:
        - schema:
            type: array
            items:
              type: string
              enum:
                - created_at
                - '-created_at'
                - updated_at
                - '-updated_at'
          in: query
          name: sort
          style: form
        - schema:
            type: integer
            maximum: 50
            minimum: 0
          in: query
          name: limit
        - schema:
            type: integer
          in: query
          name: offset
        - schema:
            type: array
            items:
              $ref: '#/components/schemas/Languages'
          in: query
          name: languages
          style: form
  /content/services:
    get:
      summary: List services
      tags:
        - Service management
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  services:
                    type: array
                    items:
                      $ref: ../models/Service.v1.yaml
              examples:
                '1':
                  value:
                    services:
                      - guid: df3a998849344e9b954b7807fc623f08
                        identifiers:
                          - source: mysource
                            id: '1'
                        metadata:
                          country: gb
                        icons:
                          - url: 'https://mydomain.com/picture.jpg'
                            width: 100
                            height: 100
                            metadata:
                              country: gb
                              language: en
                              source: mysource
                              type: icon
                        names:
                          - name: BBC One London
                            metadata:
                              language: en
                              country: gb
                        _links:
                          self:
                            href: /content/services/df3a998849344e9b954b7807fc623f08
                        created_at: '2020-01-01T00:00:00Z'
                        updated_at: '2020-01-01T00:00:00Z'
      operationId: v1.content.service.get_list
      security:
        - Authorization: []
      parameters:
        - schema:
            type: array
            items:
              type: string
              enum:
                - created_at
                - '-created_at'
                - updated_at
                - '-updated_at'
          in: query
          name: sort
          style: form
        - schema:
            type: integer
            maximum: 50
            minimum: 0
          in: query
          name: limit
        - schema:
            type: integer
          in: query
          name: offset
        - schema:
            type: array
            items:
              $ref: '#/components/schemas/Languages'
          in: query
          name: languages
          style: form
  /content/tags:
    get:
      summary: List tags
      tags:
        - Tag management
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  tags:
                    type: array
                    items:
                      $ref: ../models/Tag.v1.yaml
              examples:
                '1':
                  value:
                    tags:
                      - guid: 8703dd1ced974ecea01116f2c0a5a282
                        identifiers:
                          - source: mysource
                            id: '1'
                        names:
                          - name: Warm
                            metadata:
                              language: en
                        _links:
                          self:
                            href: /content/tags/8703dd1ced974ecea01116f2c0a5a282
                        created_at: '2020-01-01T00:00:00Z'
                        updated_at: '2020-01-01T00:00:00Z'
      operationId: v1.content.tag.get_list
      security:
        - Authorization: []
      parameters:
        - schema:
            type: array
            items:
              type: string
              enum:
                - created_at
                - '-created_at'
                - updated_at
                - '-updated_at'
          in: query
          name: sort
          style: form
        - schema:
            type: integer
            maximum: 50
            minimum: 0
          in: query
          name: limit
        - schema:
            type: integer
          in: query
          name: offset
        - schema:
            type: array
            items:
              $ref: '#/components/schemas/Languages'
          in: query
          name: languages
          style: form
  /content/genres:
    get:
      summary: List genres
      tags:
        - Genre management
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  genres:
                    type: array
                    items:
                      $ref: ../models/Genre.v1.yaml
              examples:
                '1':
                  value:
                    genres:
                      - guid: 9be42f99a8ab420082719d1bafc8e649
                        identifiers:
                          - source: mysource
                            id: '1'
                        names:
                          - metadata:
                              language: en
                            name: Action
                        _links:
                          self:
                            href: /content/genres/9be42f99a8ab420082719d1bafc8e649
                        created_at: '2020-01-01T00:00:00Z'
                        updated_at: '2020-01-01T00:00:00Z'
      operationId: v1.content.genre.get_list
      security:
        - Authorization: []
      parameters:
        - schema:
            type: array
            items:
              type: string
              enum:
                - created_at
                - '-created_at'
                - updated_at
                - '-updated_at'
          in: query
          name: sort
          style: form
        - schema:
            type: integer
            maximum: 50
            minimum: 0
          in: query
          name: limit
        - schema:
            type: integer
          in: query
          name: offset
        - schema:
            type: array
            items:
              $ref: '#/components/schemas/Languages'
          in: query
          name: languages
          style: form
  /content/content_ratings:
    get:
      summary: List content ratings
      tags:
        - Content rating management
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  content_ratings:
                    type: array
                    items:
                      $ref: ../models/ContentRating.v1.yaml
              examples:
                '1':
                  value:
                    content_ratings:
                      - guid: bcb27a2c9ee74a5a86720c3b5828093c
                        identifiers:
                          - source: mysource
                            id: '1'
                        metadata:
                          country: gb
                        organization: MPAA
                        value: '12'
                        _links:
                          self:
                            href: /content/content_ratings/bcb27a2c9ee74a5a86720c3b5828093c
                        created_at: '2020-01-01T00:00:00Z'
                        updated_at: '2020-01-01T00:00:00Z'
      operationId: v1.content.content_rating.get_list
      security:
        - Authorization: []
      parameters:
        - schema:
            type: array
            items:
              type: string
              enum:
                - created_at
                - '-created_at'
                - updated_at
                - '-updated_at'
          in: query
          name: sort
          style: form
        - schema:
            type: integer
            maximum: 50
            minimum: 0
          in: query
          name: limit
        - schema:
            type: integer
          in: query
          name: offset
        - schema:
            type: array
            items:
              $ref: '#/components/schemas/Languages'
          in: query
          name: languages
          style: form
  /content/contributors:
    get:
      summary: List contributors
      tags:
        - Contributors management
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  contributors:
                    type: array
                    items:
                      $ref: ../models/Contributor.v1.yaml
              examples:
                '1':
                  value:
                    contributors:
                      - guid: eb4aaa3de91242ba82ad48bee0b48996
                        name: Keyser Söze
                        identifiers:
                          - source: mysource
                            id: '1'
                        pictures:
                          - url: 'https://mydomain.com/picture.jpg'
                            width: 100
                            height: 100
                            metadata:
                              country: gb
                              language: en
                              type: portrait
                        _links:
                          self:
                            href: /content/contributors/eb4aaa3de91242ba82ad48bee0b48996
                        created_at: '2020-01-01T00:00:00Z'
                        updated_at: '2020-01-01T00:00:00Z'
      operationId: v1.content.contributors.get_list
      security:
        - Authorization: []
      parameters:
        - schema:
            type: array
            items:
              type: string
              enum:
                - created_at
                - '-created_at'
                - updated_at
                - '-updated_at'
          in: query
          name: sort
          style: form
        - schema:
            type: integer
            maximum: 50
            minimum: 0
          in: query
          name: limit
        - schema:
            type: integer
          in: query
          name: offset
        - schema:
            type: array
            items:
              $ref: '#/components/schemas/Languages'
          in: query
          name: languages
          style: form
  '/content/tags/{guid}':
    parameters:
      - schema:
          type: string
        name: guid
        in: path
        required: true
    get:
      summary: Get a tag
      tags:
        - Tag management
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  tag:
                    $ref: ../models/Tag.v1.yaml
              examples:
                '1':
                  value:
                    tag:
                      guid: 8703dd1ced974ecea01116f2c0a5a282
                      identifiers:
                        - source: mysource
                          id: '1'
                      names:
                        - name: Warm
                          metadata:
                            language: en
                      _links:
                        self:
                          href: /content/tags/8703dd1ced974ecea01116f2c0a5a282
                      created_at: '2020-01-01T00:00:00Z'
                      updated_at: '2020-01-01T00:00:00Z'
      operationId: v1.content.tag.get
      security:
        - Authorization: []
      parameters:
        - schema:
            type: array
            items:
              $ref: '#/components/schemas/Languages'
            minItems: 1
          in: query
          name: languages
          description: ''
          style: form
  '/content/services/{guid}':
    parameters:
      - schema:
          type: string
        name: guid
        in: path
        required: true
    get:
      summary: Get a service
      tags:
        - Service management
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  service:
                    $ref: ../models/Service.v1.yaml
              examples:
                '1':
                  value:
                    service:
                      guid: df3a998849344e9b954b7807fc623f08
                      identifiers:
                        - source: mysource
                          id: '1'
                      icons:
                        - url: 'https://mydomain.com/picture.jpg'
                          width: 100
                          height: 100
                          metadata:
                            country: gb
                            language: en
                            source: mysource
                            type: icon
                      names:
                        - name: BBC One London
                          metadata:
                            language: en
                            country: gb
                      _links:
                        self:
                          href: /content/services/df3a998849344e9b954b7807fc623f08
                      created_at: '2020-01-01T00:00:00Z'
                      updated_at: '2020-01-01T00:00:00Z'
      operationId: v1.content.service.get
      security:
        - Authorization: []
      parameters:
        - schema:
            type: array
            items:
              $ref: '#/components/schemas/Languages'
            minItems: 1
          in: query
          name: languages
          description: ''
          style: form
  '/content/genres/{guid}':
    parameters:
      - schema:
          type: string
        name: guid
        in: path
        required: true
    get:
      summary: Get a genre
      tags:
        - Genre management
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  genre:
                    $ref: ../models/Genre.v1.yaml
              examples:
                '1':
                  value:
                    genre:
                      guid: 9be42f99a8ab420082719d1bafc8e649
                      identifiers:
                        - source: mysource
                          id: '1'
                      names:
                        - metadata:
                            language: en
                          name: Action
                      _links:
                        self:
                          href: /content/genres/9be42f99a8ab420082719d1bafc8e649
                      created_at: '2020-01-01T00:00:00Z'
                      updated_at: '2020-01-01T00:00:00Z'
      operationId: v1.content.genre.get
      security:
        - Authorization: []
      parameters:
        - schema:
            type: array
            items:
              $ref: '#/components/schemas/Languages'
            minItems: 1
          in: query
          name: languages
          description: ''
          style: form
  '/content/content_ratings/{guid}':
    parameters:
      - schema:
          type: string
        name: guid
        in: path
        required: true
    get:
      summary: Get a content rating
      tags:
        - Content rating management
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  content_rating:
                    $ref: ../models/ContentRating.v1.yaml
              examples:
                '1':
                  value:
                    content_rating:
                      guid: bcb27a2c9ee74a5a86720c3b5828093c
                      identifiers:
                        - source: mysource
                          id: '1'
                      metadata:
                        country: gb
                      organization: MPAA
                      value: '12'
                      _links:
                        self:
                          href: /content/content_ratings/bcb27a2c9ee74a5a86720c3b5828093c
                      created_at: '2020-01-01T00:00:00Z'
                      updated_at: '2020-01-01T00:00:00Z'
      operationId: v1.content.content_rating.get
      security:
        - Authorization: []
      parameters:
        - schema:
            type: array
            items:
              $ref: '#/components/schemas/Languages'
            minItems: 1
          in: query
          name: languages
          description: ''
          style: form
  '/content/contributors/{guid}':
    parameters:
      - schema:
          type: string
        name: guid
        in: path
        required: true
    get:
      summary: Get a contributor
      tags:
        - Contributors management
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  contributor:
                    $ref: ../models/Contributor.v1.yaml
              examples:
                '1':
                  value:
                    contributor:
                      guid: eb4aaa3de91242ba82ad48bee0b48996
                      identifiers:
                        - source: mysource
                          id: '1'
                      name: Keyser Söze
                      pictures:
                        - url: 'https://mydomain.com/picture.jpg'
                          width: 100
                          height: 100
                          metadata:
                            country: gb
                            language: en
                            type: portrait
                      _links:
                        self:
                          href: /content/contributors/eb4aaa3de91242ba82ad48bee0b48996
                      created_at: '2020-01-01T00:00:00Z'
                      updated_at: '2020-01-01T00:00:00Z'
      operationId: v1.content.contributor.get
      security:
        - Authorization: []
      parameters:
        - schema:
            type: array
            items:
              $ref: '#/components/schemas/Languages'
            minItems: 1
          in: query
          name: languages
          description: ''
          style: form
        - schema:
            type: array
            items:
              type: string
              enum:
                - pictures
                - biographies
            minItems: 1
          in: query
          name: fields
  /content/platforms:
    get:
      summary: List platforms
      tags:
        - Platform management
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  platforms:
                    type: array
                    items:
                      $ref: ../models/Platform.v1.yaml
              examples:
                '1':
                  value:
                    platforms:
                      - guid: e1d00d49612f48c791458f8f754358a9
                        identifiers:
                          - source: mysource
                            id: '1'
                        icons:
                          - url: 'https://mydomain.com/picture.jpg'
                            width: 100
                            height: 100
                            metadata:
                              country: gb
                              language: en
                              source: mysource
                              type: icon
                        names:
                          - name: IOS
                            metadata:
                              language: en
                              country: gb
                        _links:
                          self:
                            href: /content/platforms/e1d00d49612f48c791458f8f754358a9
                        created_at: '2020-01-01T00:00:00Z'
                        updated_at: '2020-01-01T00:00:00Z'
      operationId: v1.content.platform.get_list
      security:
        - Authorization: []
      parameters:
        - schema:
            type: array
            items:
              type: string
              enum:
                - created_at
                - '-created_at'
                - updated_at
                - '-updated_at'
          in: query
          name: sort
          style: form
        - schema:
            type: integer
            maximum: 50
            minimum: 0
          in: query
          name: limit
        - schema:
            type: integer
          in: query
          name: offset
        - schema:
            type: array
            items:
              $ref: '#/components/schemas/Languages'
          in: query
          name: languages
          style: form
  '/content/platforms/{guid}':
    parameters:
      - schema:
          type: string
        name: guid
        in: path
        required: true
    get:
      summary: Get a platform
      tags:
        - Platform management
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  platform:
                    $ref: ../models/Platform.v1.yaml
              examples:
                '1':
                  value:
                    platform:
                      guid: e1d00d49612f48c791458f8f754358a9
                      identifiers:
                        - source: mysource
                          id: '1'
                      icons:
                        - url: 'https://mydomain.com/picture.jpg'
                          width: 100
                          height: 100
                          metadata:
                            country: gb
                            language: en
                            source: mysource
                            type: icon
                      names:
                        - name: IOS
                          metadata:
                            language: en
                            country: gb
                      _links:
                        self:
                          href: /content/platforms/e1d00d49612f48c791458f8f754358a9
                      created_at: '2020-01-01T00:00:00Z'
                      updated_at: '2020-01-01T00:00:00Z'
      operationId: get-content-platforms-guid
      security:
        - Authorization: []
      parameters:
        - schema:
            type: array
            items:
              $ref: '#/components/schemas/Languages'
            minItems: 1
          in: query
          name: languages
          description: ''
          style: form
  /content/locations:
    get:
      summary: List locations
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  locations:
                    type: array
                    items:
                      $ref: ../models/Location.v1.yaml
              examples:
                '1':
                  value:
                    locations:
                      - guid: e1d00d49612f48c791458f8f754358a9
                        identifiers:
                          - source: mysource
                            id: '1'
                        names:
                          - name: France
                            metadata:
                              country: fr
                        _links:
                          self:
                            href: /content/locations/e1d00d49612f48c791458f8f754358a9
                        created_at: '2020-01-01T00:00:00Z'
                        updated_at: '2020-01-01T00:00:00Z'
      operationId: v1.content.location.get_list
      security:
        - Authorization: []
      parameters:
        - schema:
            type: array
            items:
              type: string
              enum:
                - created_at
                - '-created_at'
                - updated_at
                - '-updated_at'
          in: query
          name: sort
          style: form
        - schema:
            type: integer
            maximum: 50
            minimum: 0
          in: query
          name: limit
        - schema:
            type: integer
          in: query
          name: offset
        - schema:
            type: array
            items:
              $ref: '#/components/schemas/Languages'
          in: query
          name: languages
          style: form
  '/content/locations/{guid}':
    parameters:
      - schema:
          type: string
        name: guid
        in: path
        required: true
    get:
      summary: Get a location
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  location:
                    $ref: ../models/Location.v1.yaml
              examples:
                '1':
                  value:
                    location:
                      guid: e1d00d49612f48c791458f8f754358a9
                      identifiers:
                        - source: mysource
                          id: '1'
                      names:
                        - name: France
                          metadata:
                            country: fr
                      _links:
                        self:
                          href: /content/locations/e1d00d49612f48c791458f8f754358a9
                      created_at: '2020-01-01T00:00:00Z'
                      updated_at: '2020-01-01T00:00:00Z'
      operationId: v1.content.location.get
      security:
        - Authorization: []
      parameters:
        - schema:
            type: array
            items:
              $ref: '#/components/schemas/Languages'
            minItems: 1
          in: query
          name: languages
          description: ''
          style: form
  '/content/creative_works/{guid}/tags':
    parameters:
      - schema:
          type: string
        name: guid
        in: path
        required: true
    get:
      summary: Get tags from creative work
      tags:
        - Creative work management
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  tags:
                    type: array
                    items:
                      $ref: ../models/Tag.v1.yaml
              examples:
                '1':
                  value:
                    tags:
                      - guid: 8703dd1ced974ecea01116f2c0a5a282
                        identifiers:
                          - source: mysource
                            id: '1'
                        names:
                          - name: Warm
                            metadata:
                              language: en
                        _links:
                          self:
                            href: /content/tags/8703dd1ced974ecea01116f2c0a5a282
                        created_at: '2020-01-01T00:00:00Z'
                        updated_at: '2020-01-01T00:00:00Z'
      operationId: v1.content.tag.get_from_creative_work
      security:
        - Authorization: []
  '/content/creative_works/{guid}/genres':
    parameters:
      - schema:
          type: string
        name: guid
        in: path
        required: true
    get:
      summary: Get genres from creative work
      tags:
        - Creative work management
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  genres:
                    type: array
                    items:
                      $ref: ../models/Genre.v1.yaml
              examples:
                '1':
                  value:
                    genres:
                      - guid: 9be42f99a8ab420082719d1bafc8e649
                        identifiers:
                          - source: mysource
                            id: '1'
                        names:
                          - metadata:
                              language: en
                            name: Action
                        _links:
                          self:
                            href: /content/genres/9be42f99a8ab420082719d1bafc8e649
                        created_at: '2020-01-01T00:00:00Z'
                        updated_at: '2020-01-01T00:00:00Z'
      operationId: v1.content.genre.get_from_creative_work
      security:
        - Authorization: []
  '/content/creative_works/{guid}/contributors':
    parameters:
      - schema:
          type: string
        name: guid
        in: path
        required: true
    get:
      summary: Get contributors from creative work
      tags:
        - Creative work management
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  contributors:
                    type: array
                    items:
                      $ref: ../models/Contributor.v1.yaml
              examples:
                '1':
                  value:
                    contributors:
                      - guid: eb4aaa3de91242ba82ad48bee0b48996
                        name: Keyser Söze
                        identifiers:
                          - source: mysource
                            id: '1'
                        pictures:
                          - url: 'https://mydomain.com/picture.jpg'
                            width: 100
                            height: 100
                            metadata:
                              country: gb
                              language: en
                              type: portrait
                        _links:
                          self:
                            href: /content/contributors/eb4aaa3de91242ba82ad48bee0b48996
                        created_at: '2020-01-01T00:00:00Z'
                        updated_at: '2020-01-01T00:00:00Z'
      operationId: v1.content.contributor.get_from_creative_work
      security:
        - Authorization: []
  '/content/creative_works/{guid}/content_ratings':
    parameters:
      - schema:
          type: string
        name: guid
        in: path
        required: true
    get:
      summary: Get content ratings from creative work
      tags:
        - Creative work management
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  content_ratings:
                    type: array
                    items:
                      $ref: ../models/ContentRating.v1.yaml
              examples:
                '1':
                  value:
                    content_ratings:
                      - guid: bcb27a2c9ee74a5a86720c3b5828093c
                        identifiers:
                          - source: mysource
                            id: '1'
                        metadata:
                          country: gb
                        organization: MPAA
                        value: '12'
                        _links:
                          self:
                            href: /content/content_ratings/bcb27a2c9ee74a5a86720c3b5828093c
                        created_at: '2020-01-01T00:00:00Z'
                        updated_at: '2020-01-01T00:00:00Z'
      operationId: v1.content.content_rating.get_from_creative_work
      security:
        - Authorization: []
  '/content/creative_works/{guid}/availabilities':
    parameters:
      - schema:
          type: string
        name: guid
        in: path
        required: true
    get:
      summary: Get availabilities from creative work
      tags:
        - Creative work management
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  availabilities:
                    type: array
                    items:
                      $ref: ../models/Availability.v1.yaml
                  _embedded:
                    type: array
                    items:
                      anyOf:
                        - $ref: ../models/Service.v1.yaml
                        - $ref: ../models/Platform.v1.yaml
                        - $ref: ../models/Location.v1.yaml
              examples: {}
      operationId: v1.content.availability.get_from_creative_work
      security:
        - Authorization: []
      parameters:
        - schema:
            type: array
            items:
              type: string
              enum:
                - service
                - platform
                - location
            minItems: 1
          in: query
          name: embed
          explode: false
          description: ''
          style: form
components:
  schemas:
    Languages:
      type: string
      enum:
        - ab
        - aa
        - af
        - ak
        - sq
        - am
        - ar
        - an
        - hy
        - as
        - av
        - ae
        - ay
        - az
        - bm
        - ba
        - eu
        - be
        - bn
        - bh
        - bi
        - bs
        - br
        - bg
        - my
        - ca
        - ch
        - ce
        - ny
        - zh
        - cv
        - kw
        - co
        - cr
        - hr
        - cs
        - da
        - dv
        - nl
        - dz
        - en
        - eo
        - et
        - ee
        - fo
        - fj
        - fi
        - fr
        - ff
        - gl
        - ka
        - de
        - el
        - gn
        - gu
        - ht
        - ha
        - he
        - hz
        - hi
        - ho
        - hu
        - ia
        - id
        - ie
        - ga
        - ig
        - ik
        - io
        - is
        - it
        - iu
        - ja
        - jv
        - kl
        - kn
        - kr
        - ks
        - kk
        - km
        - ki
        - rw
        - ky
        - kv
        - kg
        - ko
        - ku
        - kj
        - la
        - lb
        - lg
        - li
        - ln
        - lo
        - lt
        - lu
        - lv
        - gv
        - mk
        - mg
        - ms
        - ml
        - mt
        - mi
        - mr
        - mh
        - mn
        - na
        - nv
        - nd
        - ne
        - ng
        - nb
        - nn
        - 'no'
        - ii
        - nr
        - oc
        - oj
        - cu
        - om
        - or
        - os
        - pa
        - pi
        - fa
        - pl
        - ps
        - pt
        - qu
        - rm
        - rn
        - ro
        - ru
        - sa
        - sc
        - sd
        - se
        - sm
        - sg
        - sr
        - gd
        - sn
        - si
        - sk
        - sl
        - so
        - st
        - es
        - su
        - sw
        - ss
        - sv
        - ta
        - te
        - tg
        - th
        - ti
        - bo
        - tk
        - tl
        - tn
        - to
        - tr
        - ts
        - tt
        - tw
        - ty
        - ug
        - uk
        - ur
        - uz
        - ve
        - vi
        - vo
        - wa
        - cy
        - wo
        - fy
        - xh
        - yi
        - yo
        - za
        - zu
  securitySchemes:
    Authorization:
      name: Authorization
      type: apiKey
      in: header
      x-apikeyInfoFunc: security.check_token
